# Generated by Django 4.1.7 on 2023-03-15 21:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0002_alter_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(limit_value=3)], verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='task',
            name='summary',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(limit_value=3)], verbose_name='Краткое описание'),
        ),
    ]
