# Generated by Django 4.1.7 on 2023-03-10 01:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('issue_tracker', '0003_alter_task_project'),
    ]

    operations = [
        migrations.RunSQL('ALTER TABLE issue_tracker_task DROP COLUMN is_deleted;'),
    ]
